# Generated by Django 3.2.19 on 2023-06-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='hotel.category'),
        ),
        migrations.AlterField(
            model_name='room',
            name='featured',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Delux', 'Delux'), ('Twin', 'Twin'), ('Premium', 'Premium')], max_length=100),
        ),
    ]
