# Generated by Django 3.2.19 on 2023-06-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='featured',
        ),
    ]
